### PR TITLE
smoke tests for reading jpeg images with different libs

### PR DESCRIPTION
**Pull request by sdvillal**
I have added a small smoke test for reading jpeg images with the built package. This fails when I run directly ```conda build```. I do not know if it is intended behavior.

It works if we create manually an environment and install imagecodecs from pypi, as in:

```
conda create -n imagecodecs -c conda-forge python pip opencv pillow
conda activate imagecodecs
pip install imagecodecs
python ensure_jpegturbo_imagecodecs_plays_nicely_with_jpeg9.py 0
python ensure_jpegturbo_imagecodecs_plays_nicely_with_jpeg9.py 1
```

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Right, image codec from pypi uses turbo.

Let's not use it for pass #1.

**Comment by sdvillal** [comment]
Sounds good to me. These tests try to ensure that: 1) we can read jpeg and 2) we can read jpeg in good harmony with other libraries. Indeed, if we intend to build imagecodecs without jpeg support (which is going to cap enormously the package utility), then they are unnecessary. We should then also comment-out the runtime dependency on libjpeg-turbo.

I think these kinds of smoke-tests are actually necessary, regardless of the particular jpeg situation in conda-forge. What about keeping the tests, but disable them for the time being, to have them handy in a hopefully close future when we will be able to re-enable jpeg support?

That these tests pass with the pypi package in the environment, for which I do not know the details on how it is built, makes me think that we could take the easy and dirty workaround to use the pypi *wheel* package as a temporary basis for our conda package. But then, of course, we should add more tests, like the ones in this PR, for the different formats/libraries that might have clashing symbols in linux.

**Comment by sdvillal** [comment]
I have added some changes trying to use the latest upstream imagecodecs, that should enable us to build against jpeg. But it is failing, as I commented https://github.com/conda-forge/staged-recipes/pull/10331#issuecomment-636436721.

**Comment by sdvillal** [comment]
@hmaarrfk I have now made everything work with the latest imagecodecs upstream changes. This succeeds nicely for me locally, including adding support for jpeg. I would suggest to merge.

I also cleaned up a bit the recipe. I think we should clean the windows part and get rid of our custom copy of setup.py.

**Comment by hmaarrfk** [comment]
I understand that at loopbio, you use turbo.

Is the test applicable to conda-forge where everything is built for libjpeg?

**Pull request merged**
